app/movies/models.py
from app.extensions import db


# api imdb movies
class Movie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    seen = db.Column(db.String, nullable=False)
    orig_title = name = db.Column(db.String, nullable=False)
    name = db.Column(db.String, nullable=False)
    search = db.Column(db.String, nullable=False)
    img = db.Column(db.String, nullable=True)
    appear_type = db.Column(db.String, nullable=False)
    job = db.Column(db.String, nullable=False)
    descr = db.Column(db.String, nullable=True)
    year = db.Column(db.Integer, nullable=True)
    runtime = db.Column(db.String, nullable=True)


def commit_diff_descr(database, movies, form_movies):
    diffs = get_diff(extract_db_descr(movies), list(form_movies))
    for d in diffs:
        db_movie = database.session.execute(
            db.select(Movie).where(Movie.id == int(d[0]))
        ).scalar_one()
        db_movie.descr = d[1]
        database.session.commit()


def extract_db_descr(db_list):
    return [(str(db_item.id), db_item.descr) for db_item in db_list]


def get_diff(tuple_list_db, tuple_list_form):
    return [fd for fd in tuple_list_form if fd not in tuple_list_db]

app/movies/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, PasswordField
from wtforms.validators import DataRequired

class SearchForm(FlaskForm):
    search_text = StringField("search")

app/__init__.py
from flask import Flask
from app.extensions import db, ck, bs
import os

basedir = os.path.abspath(os.path.dirname(__file__))


class Config:
    SECRET_KEY = 'h+u5-sNA2%Fr&3"y"9nQEn==rfLjfKB{$RGShJ"$2I`d&j[5-J79:RJZoQJ('
    SQLALCHEMY_DATABASE_URI = "sqlite:///reallylikes.db"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    BOOTSTRAP_BOOTSWATCH_THEME = "lux"


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    ck.init_app(app)
    bs.init_app(app)
    with app.app_context():
        pass
        # NOTE: deploying correctly on free render.com requires turning off db drop/init with every initialization:
        # db.drop_all()
        # db.create_all()
        # init_movies(db)

    # Register blueprints here
    from app.auth import bp as auth_bp
    from app.movies import bp as movies_bp
    from app.music import bp as music_bp

    app.register_blueprint(auth_bp, url_prefix="/auth")
    app.register_blueprint(movies_bp, url_prefix="/movies")
    app.register_blueprint(music_bp, url_prefix="/music")

    @app.route("/")
    def index():
        return "<h1>Testing the Flask Application Factory Pattern</h1>"

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.main import routes

app/movies/__init__.py
from flask import Blueprint

bp = Blueprint("movies", __name__)

from app.movies import routes

app/movies/routes.py
from app.movies import bp
from flask import request, render_template, url_for, redirect, flash, session
from app.movies.forms import SearchForm
from unidecode import unidecode
from app.extensions import db
from app.movies.models import Movie, commit_diff_descr


@bp.route("/movies", methods=["GET", "POST"])
def movies():
    search_form = SearchForm()
    films = []

    # Form submitting logic:
    if request.form.get("search_submit"):
        return redirect(url_for("movies", search=request.form.get("search_text")))

    elif request.form.get("search_reset"):
        return redirect(url_for("movies"))

    else:
        films = db.session.execute(db.select(Movie).order_by(Movie.search)).scalars()
        commit_diff_descr(db, films, request.form.items())

    # View:
    search = unidecode(request.args.get("search", "")).strip().casefold()
    if search != "":
        films = db.session.execute(
            db.select(Movie)
            .order_by(Movie.search)
            .where(Movie.search.like("%" + search + "%"))
        ).scalars()
    else:
        films = db.session.execute(db.select(Movie).order_by(Movie.search)).scalars()
    return render_template("movies/movies.html", films=list(films), search_form=search_form)

# @bp.route("/movielist", methods=["GET", "POST"])
# def movielist():
#     # todo - not too elegant imo
#     if request.form.get("search_submit"):
#         books = db.session.execute(db.select(Book).order_by(Book.search).where(Book.check == "no")).scalars()
#         if len(list(books)) > 0:
#             flash("Natka nie ma jeszcze kilku książek...", "error")
#             books = db.session.execute(db.select(Book).order_by(Book.search).where(Book.check == "no")).scalars()
#             return render_template("booklist.html", books=list(books))
#         flash("Natka ma już wszystkie ksiązki!", "success")

#     # todo - not too elegant imo
#     elif request.form.get("search_reset"):
#         books = db.session.execute(db.select(Book).order_by(Book.search)).scalars()
#         return render_template("booklist.html", books=list(books))
    
#     elif request.form.__len__() > 0:
#         books = db.session.execute(db.select(Book).order_by(Book.search)).scalars()
#         commit_diff_check(db, books, request.form.items())
#     books = db.session.execute(db.select(Book).order_by(Book.search)).scalars()
#     return render_template("booklist.html", books=list(books))

app/music/__init__.py
from flask import Blueprint

bp = Blueprint("music", __name__)

from app.music import routes

app/templates/appbase.html
{% extends 'base.html' %}

{% macro static_link(img) -%}
/static/images/{{ img }}
{%- endmacro %}

{% macro api_link(img) -%}
https://image.tmdb.org/t/p/original/{{ img }}
{%- endmacro %}

{% block navbar %}

<div id="slide">
    <div class="slider-abs pt-3">
        <div class="rel pt-5">
            <p class="slider-title">Natkapp®</p>
        </div>
        {% if session.get("logged", False) %}
        <div class="rel pt-4">
            <a href="{{ url_for('logout') }}">
                <button type="button" class="btn btn-dark slider-btn">Wyloguj się</button>
                <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">❌</h4></button>
            </a>
        </div>
        <div class="rel pt-1">
        {% else %}
        <div class="rel pt-4">
        {% endif %}
            <a href="{{ url_for('index') }}">
                <button type="button" class="btn btn-dark slider-btn">Index</button>
                <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">&#10002</h4></button>
            </a>
        </div>
        <div class="rel pt-1">
            <a href="{{ url_for('movies.movies') }}">
                <button type="button" class="btn btn-dark slider-btn">Movies</button>
                <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">📚</h4></button>
            </a>
        </div>
        <div class="rel pt-1">
            <a href="{{ url_for('auth.login') }}">
                <button type="button" class="btn btn-dark slider-btn">Music</button>
                <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">🎬</h4></button>
            </a>
        </div>
        {% if not session.get("logged", False) %}
            <div class="rel pt-1">
                <a href="{{ url_for('auth.login') }}">
                    <button type="button" class="btn btn-dark slider-btn">Login</button>
                    <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">🥵</h4></button>
                </a>
            </div>
        {% endif %}
        {% if session.get("logged", False) %}
            <div class="rel pt-1">
                <button id="submitButtonText" type="submit" class="btn btn-dark slider-btn">Zapisz zmiany!</button>
                <button id="submitButtonIcon" type="submit" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">✅</h4></button>
            </div>
            <script type="text/javascript" src="{{ url_for('static', filename='scripts/onSave.js') }}"></script>
      {% endif %}
    </div>
  </div>

<div class="messages pt-4">
    {% with messages = get_flashed_messages(category_filter=["success"]) %}
    {% if messages %}
    <ul class=flashes>
        {% for message in messages %}
        <div class="success">
            <span id="tickbtn" class="closebtn-success">&#x2713</span>
            <script type="text/javascript" src="{{ url_for('static', filename='scripts/onHide.js') }}"></script>
            {{ message }}
        </div>
    {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
</div>

<div class="errors p-4">
    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
    <ul class=flashes>
        {% for error in errors %}
            <div class="error">
                <span id="closebtn" class="closebtn-error">&#x2717</span>
                <script type="text/javascript" src="{{ url_for('static', filename='scripts/onHide.js') }}"></script>
                <span> {{ error }} </span>
            </div>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            {% block styles %}
                <title>Natkapp®</title>
                <link rel="icon" href="{{ url_for('static', filename='images/fav3.png') }}">
                <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
                <link rel="stylesheet" href="{{ url_for('static', filename='styles/flashes.css') }}">
                <link rel="stylesheet" href="{{ url_for('static', filename='styles/slider.css') }}">
                <link rel="stylesheet" href="{{ url_for('static', filename='styles/tables.css') }}">
                <link rel="stylesheet" href="{{ url_for('static', filename='styles/carousel.css') }}">
                <link rel="stylesheet" href="{{ url_for('static', filename='styles/image-hover.css') }}">
                <link rel="stylesheet" href="{{ url_for('static', filename='styles/font-awesome.min.css') }}">
                {{ bootstrap.load_css() }}
            {% endblock %}
        {% endblock %}
    </head>

    <body>
        {% block navbar %}{% endblock %}
        {% block content %}{% endblock %}
        {% block scripts %}
            {{ bootstrap.load_js() }}
            {{ ckeditor.load(pkg_type="standard") }}
        {% endblock %}
    </body>
</html>

app/templates/index.html
{% extends 'appbase.html' %}

{% block content %}
<div class="abs">
  <div class="rel">
    <p>Co Natka myśli o Kunderach?</p>
  </div>
  <div class="search-carousel">
    <form class="form-inline" id="search" name="search" method="POST">
      {{ search_form.csrf_token }}
      <div class="input-group">
        {{ search_form.search_text(class_="form-search-text form-control", placeholder_="Szukaj", value=request.args.get('search', '')) }}
        <div class="input-group-append">
          <button type="submit" class="btn btn-dark btn-search-submit" name="search_submit" value="search_submit"><i class="fa fa-search fa-lg" aria-hidden="true"></i></button>
        </div>
        <div class="input-group-append">
          <button type="submit" class="btn btn-dark btn-search-reset" name="search_reset" value="search_reset"><i class="fa fa-refresh fa-lg" aria-hidden="true"></i></button>
        </div>
      </div>
    </form>
  </div>
  <div class="rel soft-page">
    <!-- Carousel -->
    <div id="carousel" class="carousel slide" data-bs-ride="carousel">

      <!-- Indicators/dots -->
      <div class="carousel-indicators">
        {% for book in books %}
        <button type="button" data-bs-target="#carousel" data-bs-slide-to="{{ loop.index-1 }}"
          class="{% if loop.index == 1 %} active {% endif %}"></button>
        {% endfor %}
      </div>

      <!-- The slideshow/carousel -->
      <div class="carousel-inner">
        <form method="POST" id="descriptions" name="descriptions">
          {% for book in books %}
          <div class="carousel-item {% if loop.index == 1 %} active {% endif %}">
            <div class="in-carousel flex">
              <img src="{{ static_link(book.img) }}" alt="For title '{{book.name}}' cover was not found" class="d-block cover">
              <div class="descr">
                {{ ckeditor.create(name=book.id, value=book.descr) }}
              </div>
            </div>
          </div>  
          {% endfor %} {{ ckeditor.load() }}
          {% if not session.get("logged", False) %}
            {% for book in books %}
              {{ ckeditor.config(name=book.id, height=300, custom_config="uiColor: '#FFFFFF', readOnly: 1") }}
            {% endfor %}
          {% else %}
            {% for book in books %}
              {{ ckeditor.config(name=book.id, height=300, custom_config="uiColor: '#058F68', readOnly: 0") }}
            {% endfor %}
          {% endif %} 

        </form>
      </div>

      <!-- Left and right controls/icons -->
      <button class="carousel-control-button carousel-control-prev" type="button" data-bs-target="#carousel"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </button>
      <button class="carousel-control-button carousel-control-next" type="button" data-bs-target="#carousel"
        data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
      </button>
    </div>

  </div>

</div>
</div>



{% endblock %}

app/templates/movies/movielist.html
{% extends 'appbase.html' %}

{% block content %}

<div class="abs">
  <div class="rel">
    <p>Pełna lista Kunderów</p>
  </div>
  <div class="rel">
    <form method="POST" id="owned" name="owned">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead class="table-header">
            <tr>
              <th scope="col" class="table-header-text">Czy Natka ma?</th>
              <th scope="col" class="table-header-title">Tytuł</th>
              <th scope="col" class="table-header-img">
                <button type="submit" class="btn btn-dark btn-search-submit" name="search_submit" value="search_submit"><i class="fa fa-info fa-3x" aria-hidden="true"></i>                </button>
                <button type="submit" class="btn btn-dark btn-search-reset" name="search_reset" value="search_reset"><i class="fa fa-refresh fa-3x" aria-hidden="true"></i></button>
              </th>
            </tr>
          </thead>
          <tbody>
            {% for book in books %}
            <tr>
              <td class="">
                <div class="input-group">
                  <select id="{{ book.id }}" name="{{ book.id }}" class="table-select table-header" {% if not session.get("logged", False) %} disabled {% endif %}>
                    <option selected value="{% if book.check == 'yes' %}yes{% else %}no{% endif %}">
                      {% if book.check =="yes" %} &#10004 {% else %} &#10008 {% endif %}</option>
                    <option value="{% if book.check == 'yes' %}no{% else %}yes{% endif %}">
                      {% if book.check == "yes" %} &#10008 {% else %} &#10004 {% endif %}</option>
                  </select>
                </div>
              </td>
              <td class="table-text">
                <a class="table-href" href="{{ url_for('index', search=book.name) }}">
                  {{ book.name }}
                </a>
              </td>
              <td class="">
                <a href="{{ url_for('index', search=book.name) }}">
                  <img src="{{ static_link(book.img) }}" alt="{{ book.name }}" class="table-img">
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </form>
  </div>
</div>



{% endblock %}

app/templates/movies/movies.html
{% extends 'appbase.html' %}

{% block content %}
<div class="abs">
  <div class="rel">
    <p>Filmy kunderskie</p>
  </div>
  <div class="search-carousel">
    <form id="search" name="search" method="POST">
      {{ search_form.csrf_token }}
      <div class="input-group">
        {{ search_form.search_text(class_="form-search-text form-control", placeholder_="Szukaj", value=request.args.get('search', '')) }}
        <div class="input-group-append">
          <button type="submit" class="btn btn-dark btn-search-submit" name="search_submit" value="search_submit"><i class="fa fa-search fa-lg" aria-hidden="true"></i></button>
        </div>
        <div class="input-group-append">
          <button type="submit" class="btn btn-dark btn-search-reset" name="search_reset" value="search_reset"><i class="fa fa-refresh fa-lg" aria-hidden="true"></i></button>
        </div>
      </div>
    </form>
  </div>
  <div class="rel soft-page">
    <!-- Carousel -->
    <div id="carousel" class="carousel slide" data-bs-ride="carousel">

      <!-- Indicators/dots -->
      <div class="carousel-indicators">
        {% for film in films %}
        <button type="button" data-bs-target="#carousel" data-bs-slide-to="{{ loop.index-1 }}"
          class="{% if loop.index == 1 %} active {% endif %}"></button>
        {% endfor %}
      </div>

      <!-- The slideshow/carousel -->
      <div class="carousel-inner">
        <form method="POST" id="descriptions" name="descriptions">
          {% for film in films %}
          <div class="carousel-item {% if loop.index == 1 %} active {% endif %}">
            <div class="in-carousel flex">
              <div class="image-container cover">
                <img class="poster d-block cover" src="{{ api_link(film.img) }}">
                <div class="gradient-layer"></div>
                <div class="description">{{film.orig_title}}, {{film.year}}, {{film.runtime}}'</div>
              </div>
              <div class="descr">
                {{ ckeditor.create(name=film.id, value=film.descr) }}
              </div>
            </div>
          </div>
          {% endfor %} {{ ckeditor.load() }}
          {% if not session.get("logged", False) %}
            {% for film in films %}
              {{ ckeditor.config(name=film.id, height=300, custom_config="uiColor: '#FFFFFF', readOnly: 1") }}
            {% endfor %}
          {% else %}
            {% for film in films %}
              {{ ckeditor.config(name=film.id, height=300, custom_config="uiColor: '#058F68', readOnly: 0") }}
            {% endfor %}
          {% endif %}
        </form>
      </div>

      <!-- Left and right controls/icons -->
      <button class="carousel-control-button carousel-control-prev" type="button" data-bs-target="#carousel"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </button>
      <button class="carousel-control-button carousel-control-next" type="button" data-bs-target="#carousel"
        data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
      </button>
    </div>

  </div>

</div>
{% endblock %}

app/templates/music/music.html
{% extends 'appbase.html' %}

{% block content %}
<div class="abs">
  <div class="rel">
    <p>Filmy kunderskie</p>
  </div>
  <div class="search-carousel">
    <form id="search" name="search" method="POST">
      {{ search_form.csrf_token }}
      <div class="input-group">
        {{ search_form.search_text(class_="form-search-text form-control", placeholder_="Szukaj", value=request.args.get('search', '')) }}
        <div class="input-group-append">
          <button type="submit" class="btn btn-dark btn-search-submit" name="search_submit" value="search_submit"><i class="fa fa-search fa-lg" aria-hidden="true"></i></button>
        </div>
        <div class="input-group-append">
          <button type="submit" class="btn btn-dark btn-search-reset" name="search_reset" value="search_reset"><i class="fa fa-refresh fa-lg" aria-hidden="true"></i></button>
        </div>
      </div>
    </form>
  </div>
  <div class="rel soft-page">
    <!-- Carousel -->
    <div id="carousel" class="carousel slide" data-bs-ride="carousel">

      <!-- Indicators/dots -->
      <div class="carousel-indicators">
        {% for film in films %}
        <button type="button" data-bs-target="#carousel" data-bs-slide-to="{{ loop.index-1 }}"
          class="{% if loop.index == 1 %} active {% endif %}"></button>
        {% endfor %}
      </div>

      <!-- The slideshow/carousel -->
      <div class="carousel-inner">
        <form method="POST" id="descriptions" name="descriptions">
          {% for film in films %}
          <div class="carousel-item {% if loop.index == 1 %} active {% endif %}">
            <div class="in-carousel flex">
              <div class="image-container cover">
                <img class="poster d-block cover" src="{{ api_link(film.img) }}">
                <div class="gradient-layer"></div>
                <div class="description">{{film.orig_title}}, {{film.year}}, {{film.runtime}}'</div>
              </div>
              <div class="descr">
                {{ ckeditor.create(name=film.id, value=film.descr) }}
              </div>
            </div>
          </div>
          {% endfor %} {{ ckeditor.load() }}
          {% if not session.get("logged", False) %}
            {% for film in films %}
              {{ ckeditor.config(name=film.id, height=300, custom_config="uiColor: '#FFFFFF', readOnly: 1") }}
            {% endfor %}
          {% else %}
            {% for film in films %}
              {{ ckeditor.config(name=film.id, height=300, custom_config="uiColor: '#058F68', readOnly: 0") }}
            {% endfor %}
          {% endif %}
        </form>
      </div>

      <!-- Left and right controls/icons -->
      <button class="carousel-control-button carousel-control-prev" type="button" data-bs-target="#carousel"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </button>
      <button class="carousel-control-button carousel-control-next" type="button" data-bs-target="#carousel"
        data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
      </button>
    </div>

  </div>

</div>
{% endblock %}

app/templates/music/musiclist.html
{% extends 'appbase.html' %}

{% block content %}

<div class="abs">
  <div class="rel">
    <p>Pełna lista Kunderów</p>
  </div>
  <div class="rel">
    <form method="POST" id="owned" name="owned">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead class="table-header">
            <tr>
              <th scope="col" class="table-header-text">Czy Natka ma?</th>
              <th scope="col" class="table-header-title">Tytuł</th>
              <th scope="col" class="table-header-img">
                <button type="submit" class="btn btn-dark btn-search-submit" name="search_submit" value="search_submit"><i class="fa fa-info fa-3x" aria-hidden="true"></i>                </button>
                <button type="submit" class="btn btn-dark btn-search-reset" name="search_reset" value="search_reset"><i class="fa fa-refresh fa-3x" aria-hidden="true"></i></button>
              </th>
            </tr>
          </thead>
          <tbody>
            {% for book in books %}
            <tr>
              <td class="">
                <div class="input-group">
                  <select id="{{ book.id }}" name="{{ book.id }}" class="table-select table-header" {% if not session.get("logged", False) %} disabled {% endif %}>
                    <option selected value="{% if book.check == 'yes' %}yes{% else %}no{% endif %}">
                      {% if book.check =="yes" %} &#10004 {% else %} &#10008 {% endif %}</option>
                    <option value="{% if book.check == 'yes' %}no{% else %}yes{% endif %}">
                      {% if book.check == "yes" %} &#10008 {% else %} &#10004 {% endif %}</option>
                  </select>
                </div>
              </td>
              <td class="table-text">
                <a class="table-href" href="{{ url_for('index', search=book.name) }}">
                  {{ book.name }}
                </a>
              </td>
              <td class="">
                <a href="{{ url_for('index', search=book.name) }}">
                  <img src="{{ static_link(book.img) }}" alt="{{ book.name }}" class="table-img">
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </form>
  </div>
</div>



{% endblock %}

templates/appbase.html
{% extends 'base.html' %}

{% macro static_link(img) -%}
/static/images/{{ img }}
{%- endmacro %}

{% macro api_link(img) -%}
https://image.tmdb.org/t/p/original/{{ img }}
{%- endmacro %}

{% block navbar %}

<div id="slide">
    <div class="slider-abs pt-3">
        <div class="rel pt-5">
            <p class="slider-title">Natkapp®</p>
        </div>
        {% if session.get("logged", False) %}
        <div class="rel pt-4">
            <a href="{{ url_for('logout') }}">
                <button type="button" class="btn btn-dark slider-btn">Wyloguj się</button>
                <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">❌</h4></button>
            </a>
        </div>
        <div class="rel pt-1">
        {% else %}
        <div class="rel pt-4">
        {% endif %}
            <a href="{{ url_for('index') }}">
                <button type="button" class="btn btn-dark slider-btn">Co Natka myśli o Kunderach?</button>
                <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">&#10002</h4></button>
            </a>
        </div>
        <div class="rel pt-1">
            <a href="{{ url_for('booklist') }}">
                <button type="button" class="btn btn-dark slider-btn">Pełna lista Kunderów u Natki</button>
                <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">📚</h4></button>
            </a>
        </div>
        <div class="rel pt-1">
            <a href="{{ url_for('movies') }}">
                <button type="button" class="btn btn-dark slider-btn">Co Natka myśli o filmach kunderskich?</button>
                <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">🎬</h4></button>
            </a>
        </div>
        {% if not session.get("logged", False) %}
            <div class="rel pt-1">
                <a href="{{ url_for('login') }}">
                    <button type="button" class="btn btn-dark slider-btn">Jesteś Natką?</button>
                    <button type="button" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">🥵</h4></button>
                </a>
            </div>
        {% endif %}
        {% if session.get("logged", False) %}
            <div class="rel pt-1">
                <button id="submitButtonText" type="submit" class="btn btn-dark slider-btn">Zapisz zmiany!</button>
                <button id="submitButtonIcon" type="submit" class="btn btn-dark slider-icon"><h4 class="slider-icon-txt">✅</h4></button>
            </div>
            <script type="text/javascript" src="{{ url_for('static', filename='scripts/onSave.js') }}"></script>
      {% endif %}
    </div>
  </div>

<div class="messages pt-4">
    {% with messages = get_flashed_messages(category_filter=["success"]) %}
    {% if messages %}
    <ul class=flashes>
        {% for message in messages %}
        <div class="success">
            <span id="tickbtn" class="closebtn-success">&#x2713</span>
            <script type="text/javascript" src="{{ url_for('static', filename='scripts/onHide.js') }}"></script>
            {{ message }}
        </div>
    {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
</div>

<div class="errors p-4">
    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
    <ul class=flashes>
        {% for error in errors %}
            <div class="error">
                <span id="closebtn" class="closebtn-error">&#x2717</span>
                <script type="text/javascript" src="{{ url_for('static', filename='scripts/onHide.js') }}"></script>
                <span> {{ error }} </span>
            </div>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
</div>
{% endblock %}